"""add title to notices

Revision ID: 19d807d4f31a
Revises: 3d6fd3b22a5f
Create Date: 2025-07-03 16:56:01.029346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d807d4f31a'
down_revision: Union[str, Sequence[str], None] = '3d6fd3b22a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('title', sa.String(), nullable=False, server_default="Sem título"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'title')
    # ### end Alembic commands ###
